# Generated by Django 6.0.7 on 2026-08-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(max_length=100)),
                ('Verse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_number', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('Lyrics', models.TextField()),
            ],
        ),
    ]
