# Generated by Django 6.1 on 2026-08-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
